server:
  servlet:
    encoding:
      charset: UTF-8

spring:
  datasource:
    url: jdbc:mariadb://workshop.c80h9shihusv.ap-northeast-2.rds.amazonaws.com:3306/workshop-db?autoReconnect=true
    driver-class-name: org.mariadb.jdbc.Driver
    username: admin
    password: root1324
  jpa:
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG