insert into team(name, leader_id)
values('1조', 'sally.kim'),
      ('2조','jyami.ho'),
      ('3조','eddie.tang'),
      ('4조','soo.u'),
      ('5조','zany.y'),
      ('6조','gray.oh');

insert into `member`(`id`, `name`, `team_name`)
values('sally.kim','샐리','1조'),
      ('steve.lim','스티브','1조'),
      ('lil.j','릴','1조'),
      ('timothy.kim','티모시','1조'),
      ('dori.k','도리','1조'),
      ('robert.kim','로버트','1조'),
      ('joe.cho','조','1조'),
      ('soonie.lee','수니','1조'),
      ('pluu.pluu','프루','1조'),
      ('jyami.ho','자미','2조'),
      ('lala.uza','라라','2조'),
      ('muzi.k','무지','2조'),
      ('iris.su','아이리스','2조'),
      ('joel.honey','조엘','2조'),
      ('dave.tgj','데이브','2조'),
      ('charlie.brown','찰리','2조'),
      ('louis.o','루이','2조'),
      ('nick.lee','닉','2조'),
      ('eddie.tang','에디','3조'),
      ('toy.w','토이','3조'),
      ('garfield.89','가필드','3조'),
      ('pi.s','파이','3조'),
      ('bale.k','베일','3조'),
      ('evelina.yo','이블리나','3조'),
      ('mia.song','미아','3조'),
      ('timmy.oh','티미','3조'),
      ('soo.u','수','4조'),
      ('jackson.hyun','잭슨','4조'),
      ('show.pang','쇼','4조'),
      ('juniel.y','주니엘','4조'),
      ('bernard.park','버나드','4조'),
      ('claire.w','왕클','4조'),
      ('soy.h','소이','4조'),
      ('luffy.hee','루피','4조'),
      ('issac.k','이삭','4조'),
      ('zany.y','자니','5조'),
      ('alice.lee','앨리스','5조'),
      ('caron.k','카론','5조'),
      ('zachary.kim','재커리','5조'),
      ('ditto.132','디토','5조'),
      ('jino.h','지노','5조'),
      ('ever.land','에버','5조'),
      ('zed.k','제드','5조'),
      ('gray.oh','그레이','6조'),
      ('dew.lee','듀','6조'),
      ('dean.h','딘','6조'),
      ('crystal.y','크리스탈','6조'),
      ('brandon.kim','브랜든','6조'),
      ('claire.h','트클','6조'),
      ('zoe.lim','쪼이','6조'),
      ('azki.org','아즈키','6조'),
      ('aiden.k','에이든','6조');

insert into `game`(`title`, `description`, `image`, `time`, `type`)
values ('사전미션', '처음 뵙겠습니다!', 'team_work.png', 1, 'TEAM'),
       ('깃발 꾸미기', '팀원들과 깃발을 꾸미며 친해져봐요.', 'color-pen.png', 5, 'TEAM'),
       ('수학문제', '우리 모두 덧셈 뺄셈은 할 수 있잖아요?', 'math.png', 20, 'TEAM'),
       ('OX 퀴즈', '당신의 지성미를 마음껏 뽐내봐요.', 'xo-game.png', 20, 'PERSONAL'),
       ('선착순 호루라기', '순발력이 없으면 살아남을 수 없어요.', 'whistle.png', 10, 'PERSONAL'),
       ('판 뒤집기', '판 뒤집기 전쟁, 다쳐도 몰라요', 'color-board.jpeg', 20, 'TEAM'),
       ('표정 맞추기', '홈캠프의 명배우는 누구일까요', 'trick_face_w.png', 5, 'TEAM');