name: homecamp workshop server

on:
  push:
    branches: [ "main" ] # main에 push가 될 때 CD가 일어나도록 핸들링

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2

      - name: Setup Java JDK
        uses: actions/setup-java@v1.4.4
        with:
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: Build with Gradle
        run: ./gradlew clean build
        shell: bash

      - name: Make Directory for deliver
        run: mkdir deploy

      - name: Copy Jar
        run: cp ./build/libs/*.jar ./deploy/

      - name: Make zip file
        run: zip -r -qq -j ./app-build.zip ./deploy

      - name: Deliver to AWS S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp --region ap-northeast-2 --acl private ./app-build.zip s3://deploy-bucket-home-workshop/

      - name: Deploy to AWS EC2 from S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws deploy create-deployment --application-name workshop-server --deployment-config-name CodeDeployDefault.AllAtOnce --deployment-group-name workshop-server-group --s3-location bucket=s3://deploy-bucket-home-workshop,key=$GITHUB_SHA.zip,bundleType=zip