name: homecamp workshop server

on:
  push:
    branches: [ "main" ] # main에 push가 될 때 CD가 일어나도록 핸들링

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2

      - name: Setup Java JDK
        uses: actions/setup-java@v1.4.4
        with:
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: Build with Gradle
        run: ./gradlew clean build
        shell: bash

      - name: Get current time
        uses: josStorer/get-current-time@v2.1.1
        id: current-time
        with:
          format: YYYY-MM-DDTHH-mm-ss
          utcOffset: "+09:00"

      - name: Generate deployment package
        run: |
          sudo mkdir deploy
          cp ./build/libs/*.jar ./deploy/application.jar
          cp Procfile ./deploy/Procfile
          cp -r .ebextensions ./deploy/.ebextensions
          cp -r .platform ./deploy/.platform
          cd deploy && zip -r deploy.zip .

      - name: Beanstalk Deploy
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: home-workshop-server
          environment_name: Home-workshop-server-env
          version_label: Github Action-${{steps.current-time.outputs.formattedTime}}
          region: ap-northeast-2
          deployment_package: deploy/deploy.zip
          wait_for_environment_recovery: 180